### ISSUE TITLE
Move FSharp.Data to FsLab

### ISSUE THREAD

**Issue by sergey-tihon** [fslaborg/fslaborg.admin#1]
I think that `fslaborg` is the better place for `FSharp.Data` than `fsharp` org.
You thoughts @tpetricek @ovatsus @dsyme?

**Comment by dsyme** [comment]
I'm probably ok with it either way, and ultimately it's up to @tpetricek and @ovatsus as primary owners.  

I tend to think of FSharp.Data as a very, very central library for F# - essentially part of the core library itself - and it has many uses which are much broader than data science.  

So it depends a bit on whether fslaborg is happy to own libraries that are very broad in scope, and to curate them from that perspective. I think it is and so it would probably be a good move.

**Comment by tpetricek** [comment]
I'm also not entirely sure about F# Data - it is definitely a part of the FsLab story (and it would certainly be nice to have it here - though perhaps with existing owners including @fsgit and @fsprojects/owners). 

But the library is certainly useful outside of data science and I would really like to avoid creating an impression that it is useful _only_ in that context. But that is perhaps better addressed by having C# interop, Web programming & other samples on F# Data page.

Another question is, do we want to move http://fsharp.github.io/FSharp.Data/ to http://fslab.org/FSharp.Data ?

(I'm happy with both... but if we want to keep "fsharp" for compiler & core library, then "fslaborg" is certainly a natural place.)

**Comment by ovatsus** [comment]
I think F# Data is roughly 50% data science and 50% web programming, and while it definitely should be part of the fslab package and be referenced on the site as one of the big components of it, I'm not sure about moving the ownership to fslab.org entirely, we do get a fair share of pull request and issues from people only using it for the json and the http stuff in a non-data science context... It's also at a grown up state with enough links to it to cause any move to always be a bit painful
Having said that, I don't particularly oppose if it's moved, I'd say I'm 60% for keeping it as is, 40% for moving it
